"use client"

import React, { useState, useEffect } from "react"
import { useAuth } from "@/contexts/auth-context"
import { usePermissions } from "@/contexts/permission-context"
import { reportService, type BulkCommentRequest } from "@/services/report.service"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Switch } from "@/components/ui/switch"
import { Separator } from "@/components/ui/separator"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { 
  Save, 
  Loader2, 
  AlertCircle, 
  CheckCircle,
  Search,
  Users,
  MessageSquare,
  CheckCheck,
  Sparkles,
  Wand2,
  Info,
  X,
  FileText
} from "lucide-react"
import { cn } from "@/lib/utils"

interface Student {
  id: string
  firstName: string
  lastName: string
  studentNumber: string
  comment?: string
}

interface GeneralComment {
  id: string
  comment: string
  isActive: boolean
  teacher: {
    firstName: string
    lastName: string
  }
}

interface MarkBasedSuggestion {
  averageMark: number
  grade: string
  descriptor: string
  suggestedComment: string
}

interface BulkTeacherCommentsProps {
  classId: string
  year: number
  term: number
  students: Student[]
  onSave?: () => void
}

export function BulkTeacherComments({ 
  classId, 
  year, 
  term,
  students,
  onSave 
}: BulkTeacherCommentsProps) {
  const { user } = useAuth()
  
  const [loading, setLoading] = useState({
    fetching: false,
    saving: false,
    generating: false,
    fetchingGeneral: false
  })
  
  const [searchQuery, setSearchQuery] = useState("")
  const [studentComments, setStudentComments] = useState<Map<string, string>>(new Map())
  const [generalComment, setGeneralComment] = useState<GeneralComment | null>(null)
  const [generalCommentText, setGeneralCommentText] = useState("")
  const [generalCommentActive, setGeneralCommentActive] = useState(false)
  const [hasChanges, setHasChanges] = useState(false)
  const [saveStatus, setSaveStatus] = useState<"idle" | "success" | "error">("idle")
  const [errorMessage, setErrorMessage] = useState("")
  const [savedCount, setSavedCount] = useState(0)
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)
  const [autoGenerateResults, setAutoGenerateResults] = useState<any>(null)

  // Determine user's capabilities via permissions
  const { hasAnyPermission } = usePermissions()
  const isHeadTeacher = hasAnyPermission("reports.manage_settings")
  const isClassTeacher = !isHeadTeacher
  const userRole = isHeadTeacher ? "head_teacher" : "class_teacher"

  // Load existing comments and general comment
  useEffect(() => {
    loadComments()
    loadGeneralComment()
  }, [classId, year, term])

  const loadComments = async () => {
    setLoading(prev => ({ ...prev, fetching: true }))
    setErrorMessage("")
    
    try {
      const comments = await reportService.getClassComments(
        classId,
        year,
        term,
        userRole
      )

      // Map specific comments to students
      const commentMap = new Map<string, string>()
      comments.forEach(comment => {
        commentMap.set(comment.studentId, comment.comment)
      })
      
      setStudentComments(commentMap)
      setHasChanges(false)
      setSaveStatus("idle")
    } catch (error: any) {
      setErrorMessage(error.message || "Failed to load comments")
      console.error("Error loading comments:", error)
    } finally {
      setLoading(prev => ({ ...prev, fetching: false }))
    }
  }

  const loadGeneralComment = async () => {
    setLoading(prev => ({ ...prev, fetchingGeneral: true }))
    
    try {
      const comment = await reportService.getGeneralComment(
        classId,
        year,
        term,
        userRole
      )

      if (comment) {
        setGeneralComment(comment)
        setGeneralCommentText(comment.comment)
        setGeneralCommentActive(comment.isActive)
      }
    } catch (error: any) {
      // General comment not found is okay
      console.log("No general comment found")
    } finally {
      setLoading(prev => ({ ...prev, fetchingGeneral: false }))
    }
  }

  const handleCommentChange = (studentId: string, value: string) => {
    setStudentComments(prev => {
      const newMap = new Map(prev)
      newMap.set(studentId, value)
      return newMap
    })
    setHasChanges(true)
    setSaveStatus("idle")
  }

  const handleSaveGeneralComment = async () => {
    if (!generalCommentText.trim()) {
      setErrorMessage("General comment cannot be empty")
      return
    }

    setLoading(prev => ({ ...prev, saving: true }))
    setErrorMessage("")

    try {
      const result = await reportService.saveGeneralComment({
        classId,
        year,
        term,
        comment: generalCommentText
      })

      setGeneralComment(result)
      setGeneralCommentActive(result.isActive)
      setSaveStatus("success")
      
      setTimeout(() => {
        setSaveStatus("idle")
      }, 3000)
    } catch (error: any) {
      setErrorMessage(error.message || "Failed to save general comment")
      setSaveStatus("error")
    } finally {
      setLoading(prev => ({ ...prev, saving: false }))
    }
  }

  const handleToggleGeneralComment = async () => {
    if (!generalComment) return

    setLoading(prev => ({ ...prev, saving: true }))

    try {
      await reportService.toggleGeneralComment(
        classId,
        year,
        term,
        userRole,
        !generalCommentActive
      )

      setGeneralCommentActive(!generalCommentActive)
    } catch (error: any) {
      setErrorMessage(error.message || "Failed to toggle general comment")
    } finally {
      setLoading(prev => ({ ...prev, saving: false }))
    }
  }

  const handleBulkSave = async () => {
    const commentsToSave: BulkCommentRequest[] = []
    
    // Only save non-empty specific comments
    studentComments.forEach((comment, studentId) => {
      if (comment.trim()) {
        commentsToSave.push({
          studentId,
          comment: comment.trim()
        })
      }
    })

    if (commentsToSave.length === 0) {
      setErrorMessage("No specific comments to save")
      return
    }

    setLoading(prev => ({ ...prev, saving: true }))
    setErrorMessage("")
    setSaveStatus("idle")

    try {
      const result = await reportService.bulkSaveTeacherComments(
        classId,
        year,
        term,
        commentsToSave
      )

      setSavedCount(result.count)
      setHasChanges(false)
      setSaveStatus("success")
      
      if (onSave) {
        onSave()
      }

      setTimeout(() => {
        setSaveStatus("idle")
      }, 5000)
    } catch (error: any) {
      setErrorMessage(error.message || "Failed to save comments")
      setSaveStatus("error")
    } finally {
      setLoading(prev => ({ ...prev, saving: false }))
    }
  }

  const handleAutoGenerate = async () => {
    setLoading(prev => ({ ...prev, generating: true }))
    setErrorMessage("")

    try {
      const results = await reportService.autoGenerateComments(
        classId,
        year,
        term,
        false // Don't overwrite existing
      )

      setAutoGenerateResults(results)
      setShowAutoGenerateDialog(true)

      // Reload comments to show generated ones
      await loadComments()
    } catch (error: any) {
      setErrorMessage(error.message || "Failed to auto-generate comments")
    } finally {
      setLoading(prev => ({ ...prev, generating: false }))
    }
  }

  const handleClearSpecificComment = (studentId: string) => {
    setStudentComments(prev => {
      const newMap = new Map(prev)
      newMap.delete(studentId)
      return newMap
    })
    setHasChanges(true)
  }

  // Filter students based on search
  const filteredStudents = students.filter(student => {
    if (!searchQuery) return true
    const query = searchQuery.toLowerCase()
    return (
      student.firstName.toLowerCase().includes(query) ||
      student.lastName.toLowerCase().includes(query) ||
      student.studentNumber.toLowerCase().includes(query)
    )
  })

  // Count students with specific comments
  const studentsWithSpecificComments = Array.from(studentComments.values()).filter(c => c.trim()).length
  const studentsWithGeneralOnly = generalCommentActive ? 
    students.length - studentsWithSpecificComments : 0

  if (loading.fetching) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <div className="text-center space-y-2">
            <Loader2 className="h-8 w-8 animate-spin mx-auto text-muted-foreground" />
            <p className="text-sm text-muted-foreground">Loading comments...</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-4">
      {/* Status Messages */}
      {errorMessage && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>{errorMessage}</AlertDescription>
        </Alert>
      )}

      {saveStatus === "success" && (
        <Alert className="border-green-200 bg-green-50 text-green-900">
          <CheckCircle className="h-4 w-4" />
          <AlertDescription>
            Successfully saved {savedCount} comment{savedCount !== 1 ? 's' : ''}
          </AlertDescription>
        </Alert>
      )}

      {/* General Comment Card */}
      <Card className="border-blue-200">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-blue-600" />
              <CardTitle>General Comment</CardTitle>
            </div>
            {generalComment && (
              <div className="flex items-center gap-2">
                <Label htmlFor="general-active" className="text-sm">
                  Apply to all
                </Label>
                <Switch
                  id="general-active"
                  checked={generalCommentActive}
                  onCheckedChange={handleToggleGeneralComment}
                  disabled={loading.saving}
                />
              </div>
            )}
          </div>
          <CardDescription>
            Set a default comment for all students. Students with specific comments will override this.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea
            value={generalCommentText}
            onChange={(e) => setGeneralCommentText(e.target.value)}
            placeholder="Enter a general comment that applies to all students..."
            rows={4}
            disabled={loading.saving}
            className="resize-none"
          />
          
          <div className="flex gap-2">
            <Button
              onClick={handleSaveGeneralComment}
              disabled={!generalCommentText.trim() || loading.saving}
              size="sm"
            >
              {loading.saving ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Saving...
                </>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  Save General Comment
                </>
              )}
            </Button>
          </div>

          {generalCommentActive && (
            <Alert className="bg-blue-50 border-blue-200">
              <Info className="h-4 w-4 text-blue-600" />
              <AlertDescription className="text-blue-900">
                This general comment is active and will apply to {studentsWithGeneralOnly} student{studentsWithGeneralOnly !== 1 ? 's' : ''} without specific comments.
              </AlertDescription>
            </Alert>
          )}
        </CardContent>
      </Card>

      {/* Header Card */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Users className="h-5 w-5" />
              <CardTitle>Specific Comments</CardTitle>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="outline">
                {studentsWithSpecificComments} specific
              </Badge>
              {generalCommentActive && (
                <Badge variant="secondary">
                  {studentsWithGeneralOnly} general
                </Badge>
              )}
            </div>
          </div>
          <CardDescription>
            Add {userRole === "head_teacher" ? "head teacher" : "class teacher"} comments for individual students (Year {year}, Term {term})
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Search */}
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search students..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9"
            />
          </div>

          {/* Quick Actions */}
          <div className="flex flex-wrap gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleBulkSave}
              disabled={!hasChanges || loading.saving}
            >
              {loading.saving ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Saving...
                </>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  Save Specific Comments
                </>
              )}
            </Button>

            {isClassTeacher && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleAutoGenerate}
                disabled={loading.generating}
                className="bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200"
              >
                {loading.generating ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Wand2 className="h-4 w-4 mr-2" />
                    Auto-Generate from Marks
                  </>
                )}
              </Button>
            )}
          </div>

          {hasChanges && (
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                You have unsaved changes. Click "Save Specific Comments" to update.
              </AlertDescription>
            </Alert>
          )}
        </CardContent>
      </Card>

      {/* Students List */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <MessageSquare className="h-4 w-4" />
            Student Comments ({filteredStudents.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ScrollArea className="h-[600px] pr-4">
            <div className="space-y-4">
              {filteredStudents.map((student, index) => {
                const comment = studentComments.get(student.id) || ""
                const hasSpecificComment = comment.trim().length > 0
                const willUseGeneral = !hasSpecificComment && generalCommentActive

                return (
                  <div key={student.id} className="space-y-2">
                    {index > 0 && <div className="border-t my-4" />}
                    
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Label className="font-medium">
                          {student.firstName} {student.lastName}
                        </Label>
                        <Badge variant="outline" className="text-xs">
                          {student.studentNumber}
                        </Badge>
                        {hasSpecificComment && (
                          <CheckCheck className="h-4 w-4 text-green-600" />
                        )}
                        {willUseGeneral && (
                          <Badge variant="secondary" className="text-xs">
                            Using general
                          </Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-2">
                        {hasSpecificComment && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleClearSpecificComment(student.id)}
                            disabled={loading.saving}
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        )}
                        <span className="text-xs text-muted-foreground">
                          {comment.length} chars
                        </span>
                      </div>
                    </div>

                    <Textarea
                      value={comment}
                      onChange={(e) => handleCommentChange(student.id, e.target.value)}
                      placeholder={willUseGeneral ? "Leave empty to use general comment..." : `Enter specific comment for ${student.firstName}...`}
                      rows={3}
                      disabled={loading.saving}
                      className={cn(
                        "resize-none text-sm",
                        hasSpecificComment && "border-green-200 bg-green-50/50"
                      )}
                    />
                  </div>
                )
              })}

              {filteredStudents.length === 0 && (
                <div className="text-center py-8 text-muted-foreground">
                  <Search className="h-8 w-8 mx-auto mb-2 opacity-50" />
                  <p>No students found matching "{searchQuery}"</p>
                </div>
              )}
            </div>
          </ScrollArea>
        </CardContent>
      </Card>

      {/* Auto-Generate Results Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-600" />
              Auto-Generation Results
            </DialogTitle>
            <DialogDescription>
              Mark-based comments have been generated for students
            </DialogDescription>
          </DialogHeader>

          {autoGenerateResults && (
            <div className="space-y-4">
              <div className="grid grid-cols-3 gap-4">
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-green-600">
                        {autoGenerateResults.generated?.length || 0}
                      </div>
                      <div className="text-sm text-muted-foreground">Generated</div>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-yellow-600">
                        {autoGenerateResults.skipped?.length || 0}
                      </div>
                      <div className="text-sm text-muted-foreground">Skipped</div>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="pt-6">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-red-600">
                        {autoGenerateResults.errors?.length || 0}
                      </div>
                      <div className="text-sm text-muted-foreground">Errors</div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {autoGenerateResults.generated?.length > 0 && (
                <div>
                  <h4 className="font-medium mb-2">Generated Comments</h4>
                  <ScrollArea className="h-[200px]">
                    <div className="space-y-2">
                      {autoGenerateResults.generated.map((item: any) => (
                        <div key={item.studentId} className="text-sm p-2 bg-green-50 rounded">
                          <div className="font-medium">{item.studentName}</div>
                          <div className="text-xs text-muted-foreground">
                            Average: {item.averageMark}% ({item.grade})
                          </div>
                          <div className="text-xs mt-1">{item.comment}</div>
                        </div>
                      ))}
                    </div>
                  </ScrollArea>
                </div>
              )}
            </div>
          )}

          <DialogFooter>
            <Button onClick={() => setShowAutoGenerateDialog(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}